"""Vector parity against the browser embedding path.

This is the gate the whole service ships behind. LockIn already has vectors in
its database, written by `lib/llm/wasm-embedder.ts` in users' browsers. If this
service embeds into even a slightly different space, retrieval degrades without
a single error being raised — the vectors are still 384-dimensional, still
normalised, and every assertion in the TypeScript still passes.

Fixtures are generated by `scripts/generate_fixtures.mjs`, which runs the exact
library the browser runs. Regenerate them if the model, pooling, or query prefix
ever changes.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from app.config import EMBEDDING_DIMS, EMBEDDING_MODEL, QUERY_PREFIX
from app.embed import build_embed_input, embedder

FIXTURES_PATH = Path(__file__).parent / "fixtures" / "parity.json"

# Two fp32 runtimes (onnxruntime here, onnxruntime-web in the browser) will not
# agree bit-for-bit; they accumulate float error differently. 0.999 cosine is
# far tighter than any real drift between them and far looser than the ~0.7 a
# pooling or prefix mistake would produce, so it separates the two cleanly.
COSINE_FLOOR = 0.999


@pytest.fixture(scope="module")
def reference() -> dict:
    if not FIXTURES_PATH.exists():
        pytest.fail(
            f"Missing {FIXTURES_PATH}. Generate it from the repo root with:\n"
            "  node service/scripts/generate_fixtures.mjs"
        )
    return json.loads(FIXTURES_PATH.read_text())


def cosine(a: list[float], b: list[float]) -> float:
    va, vb = np.asarray(a, dtype=np.float64), np.asarray(b, dtype=np.float64)
    return float(va @ vb / (np.linalg.norm(va) * np.linalg.norm(vb)))


def test_fixtures_describe_the_expected_configuration(reference: dict) -> None:
    """A fixture file generated under different settings would silently pass."""
    assert reference["model"] == EMBEDDING_MODEL
    assert reference["dims"] == EMBEDDING_DIMS
    assert reference["query_prefix"] == QUERY_PREFIX
    assert reference["pooling"] == "cls"
    assert reference["normalize"] is True


def test_query_prefix_is_applied_to_queries_only() -> None:
    assert build_embed_input("abc", "query") == f"{QUERY_PREFIX} abc"
    assert build_embed_input("abc", "passage") == "abc"


def test_matches_browser_vectors(reference: dict) -> None:
    """Every fixture, embedded one at a time, matches the browser's vector."""
    failures = []
    for case in reference["fixtures"]:
        actual = embedder.embed([case["text"]], case["role"])[0]
        assert len(actual) == EMBEDDING_DIMS
        score = cosine(actual, case["vector"])
        if score < COSINE_FLOOR:
            failures.append(f"  [{case['role']}] {case['text'][:56]!r} → cosine {score:.6f}")

    assert not failures, "Vectors diverge from the browser path:\n" + "\n".join(failures)


def test_vectors_are_normalised(reference: dict) -> None:
    """Scoring downstream is a bare dot product (lib/rag/similarity.ts), which
    is only cosine similarity if every vector is unit length."""
    texts = [c["text"] for c in reference["fixtures"] if c["role"] == "passage"]
    for vector in embedder.embed(texts, "passage"):
        assert np.linalg.norm(vector) == pytest.approx(1.0, abs=1e-5)


def test_batching_does_not_change_vectors(reference: dict) -> None:
    """Padding a short text alongside a long one must not move its vector.

    This is the assumption that makes batching safe, and it holds only because
    attention_mask is fed to the model. Drop that input and this test is the
    only thing that notices.
    """
    cases = [c for c in reference["fixtures"] if c["role"] == "passage"]
    batched = embedder.embed([c["text"] for c in cases], "passage")

    for case, from_batch in zip(cases, batched, strict=True):
        alone = embedder.embed([case["text"]], "passage")[0]
        assert cosine(alone, from_batch) >= COSINE_FLOOR, (
            f"Batching moved the vector for {case['text'][:56]!r}"
        )


def test_empty_batch_is_not_a_model_call() -> None:
    assert embedder.embed([], "passage") == []


def test_over_length_input_is_sliced_not_re_terminated() -> None:
    """Pins the truncation semantics that parity depends on.

    `tokenizers`' built-in truncation would keep [CLS] + body + [SEP]. The
    browser slices instead, dropping [SEP]. `test_matches_browser_vectors`
    catches a regression here too, but only as a mysterious cosine drop on one
    fixture — this says what actually broke.
    """
    embedder.load()
    tokenizer = embedder._tokenizer
    assert tokenizer is not None

    sep_id = tokenizer.token_to_id("[SEP]")
    over_length = "the mitochondrion is the powerhouse of the cell. " * 200
    ids = tokenizer.encode(over_length).ids[: embedder._max_length]

    assert len(ids) == embedder._max_length
    assert ids[-1] != sep_id, (
        "Truncation re-terminated the sequence with [SEP]; the browser does not, "
        "and vectors will no longer match the stored corpus."
    )
